[versions]
kotlin = "1.3.72"

[libraries.kotlin-gradle]
version.ref = "kotlin"
module = "org.jetbrains.kotlin:kotlin-gradle-plugin"

[libraries.kotlin-test-core]
version.ref = "kotlin"
module = "org.jetbrains.kotlin:kotlin-test"

[libraries.kotlin-test-junit]
version.ref = "kotlin"
module = "org.jetbrains.kotlin:kotlin-test-junit"

[libraries.subatomic]
version = "1.0.0"
module = "com.github.inkapplications.subatomic:core"
